### ISSUE TITLE
2.5.0 Config with YAML file CustomizableLayout : pb properties dateFormat and template

### ISSUE THREAD

**Issue by franck-benault** [audit4j/audit4j-core#71]
Hello

with Audit4j version 2.5.0
when I am using a config with YAML file
for CustomizableLayout, I cannot use the properties dateFormat and template

YAML example file 
```
!Configuration # Mandatory
 
# Configure handlers, One or more handlers must be configured.
handlers:
- !org.audit4j.core.handler.ConsoleAuditHandler {}
 
# Configure handlers, Either one handler must be configured.
layout: !org.audit4j.core.layout.CustomizableLayout
   dateFormat: yyyy/MM/dd HH:mm:ss
   template: ${eventDate}|${uuid}|${actor}|${action}|${origin} => ${foreach fields field}[${field.name}:${field.value}]${end}
 
# Configure meta data.
metaData: !org.audit4j.core.DummyMetaData {}
 ```
root cause:
missing getter for the fields dateFormat and template in CustomizableLayout class

Regards Franck
